grain-lang/binaryen.ml

- binaryen.opam
- esy.json
- esy.lock/index.json
- esy.lock/opam/conf-cmake.1/files/configure.sh
- esy.lock/opam/conf-cmake.1/opam
This fixes the opam file via feedback from https://github.com/ocaml/opam-repository/pull/16637.
> Fix opam dune version and add cmake as a build dependency

- dune
- dune-project
- dune-workspace
- src/dune
- test/dune
- test/test.expected
- virtual/dune
- virtual/export.mli
- virtual/expression.mli
- virtual/features.mli
- virtual/function.mli
- virtual/function_table.mli
- virtual/global.mli
- virtual/import.mli
- virtual/literal.mli
- virtual/memory.mli
- virtual/module.mli
- virtual/op.mli
- virtual/type.mli
This adds a virtual interface to the Binaryen.ml package and renames the native implementation as `binaryen.native`. This is set as the default implementation so people can depend on `binaryen` without pulling in native explicitly, but sets us up to add JS support in my next PR.
> Add dune virtual interfaces

- .github/workflows/esy.yml
Found a typo that that continued to build deps even when pulled from cache.
> Fix typo in esy workflow

- package.json
I had a bug in my publish to npm, so I needed to fix it and bump the patch version.
I'm not trying to solve the problem of aligning versions right now and we'll be cutting a binaryen.ml 0.4 with the upstream changes once they version binaryen 99 and we will push that out to everywhere.
> Bump version for failed npm publish

- .github/workflows/release.yml
The Actions security changes broke our release workflow. I think this will fix it.
> ci: use maintained action

- README.md
Just documenting my discoveries about static linking.
> docs: add section about static linking

- .github/workflows/opam-publish.yml
My [opam-publish patch](https://github.com/ocaml-opam/opam-publish/pull/110) landed awhile ago. This removes 1 hack in our workflow for automated publishes.
> chore: Add --no-browser flag to opam-publish

- .github/workflows/release.yml
Trying to roll this up into a PR to stop picking up my binaryen changes from 0.4.0
> ci: Add release-please-action to release process

- .github/workflows/opam-publish.yml
- .github/workflows/opam.yml
For some reason the opam builds won't succeed on GitHub's Ubuntu 20.04 due to some `undefined symbol: pthreads_create` error.
I can't figure out why this is the case, so let's just revert to Ubuntu 18.04 for opam flows.
> ci: run opam build on ubuntu 18 instead of 20

- .github/workflows/release.yml
I don't actually know if this will work.
> ci: fix markdown escaping for opam release

- js/expression.ml
- src/binaryen_stubs_expressions.c
- src/dune
- src/expression.ml
- vendor/binaryen-c.h
- vendor/wasm-delegations.h
- virtual/expression.mli
BREAKING CHANGE: Table name must now be provided to the `Expression.call_indirect` and `Expression.return_call_indirect` instructions.
> feat: Upgrade to Binaryen 100

- js/expression.ml
- package.json
- src/config/library_flags.ml
- src/dune
- src/expression.ml
- test/test.ml
- virtual/expression.mli
> chore: fix formatter & format the code

- js/expression.ml
- test/test.expected
- test/test.ml
Binaryen.js uses a JavaScript `null` for the null expression, so we just use a pure JS value for this.
I want to add a test for this, but I need @ospencer's help.
> fix(js): return JS null value from Expression.null

- js/function_table.ml
- src/function_table.ml
- virtual/function_table.mli
This adds an `unlimited` constant value to `Function_table` because the value you need to use for "unlimited" is `-1`. This is now the same as `Memory.unlimited`
> feat: add Function_table.unlimited constant

- js/dune
- js/module.ml
- js/stubs.c
This switches the hand-rolled encoding stuff to just defer to the JSOO externals. We don't use the `read` method in Grain, so that isn't tested (so I left the comment that we need to check it), but I believe the other 2 are exercised in the Grain codebase.
> fix(js): utilize JSOO externals to convert between uint8array & bytes

- js/expression.ml
- js/table.ml
- src/binaryen_stubs_tables.c
- src/dune
- src/table.ml
- test/test.expected
- test/test.ml
- virtual/dune
- virtual/table.mli
This fixes the JS version of `call_indirect` methods by properly converting the table name OCaml string to a JS string.
I want to add a test for this but I need @ospencer's help.
> fix(js): cast the call_indirect string arguments to JS strings

- js/expression.ml
- src/expression.ml
- virtual/expression.mli
Rip `global_get_get_this_bread` ☠️
> Expression api updates

- .github/workflows/opam.yml
This bumps setup-ocaml to v2 which handles the dep installs automatically and has better support for `opam depext` (which we need for #113)
> chore(ci): Update opam workflow

- .github/workflows/release.yml
Github disabled this protocol and broke the workflow.
Closes #114
> chore: Replace git:// protocol in release workflow

- package.json
This just adds a publishConfig to the package.json (in case we copy-paste this project into another).
Closes #115
> chore: Add publishConfig for our package.json

- js/module.ml
- src/module.ml
There are currently 14 Binaryen features, so this shouldn't break unless that number expands to 32, which is fairly unlikely.
> fix: Make features work in 32-bit mode

- .github/workflows/opam.yml
- binaryen.opam
In https://github.com/ocaml/opam-repository/pull/20447, the opam team removed our upper bounds on ocaml version. This aligns it.
> chore: Allow ocaml 4.13 in opam

- js/dune
- js/postlude.js
- js/prelude.js
I'm trying some tweaks for our JSOO build in non-nodejs environments.
> fix: Handle JS global in non-node environments

- .github/workflows/release.yml
ReleasePlease v13 renamed `body` to `notes` (or so it seemed) but those aren't actually provided anymore, as I found in my last release.
Instead, I decided to fork the `upload-release-action` that we wanted to use and stripped out a bunch of cruft, updated the deps, and exported the body from the release that it fetches.
> chore: Update upload-release-action to our fork

- README.md
- test/config/ocamlopt_flags.ml
This adds some additional flags to our tests and documents them in the README. I started noticing that we get these warnings and someone on https://discuss.ocaml.org/t/compact-unwind-on-macos/9237/2 said that they probably shouldn't cause errors.
I added the `-no_compact_unwind` flag, but that caused the tests to fail, so I added back the `-keep_dwarf_unwind` which seems to be working.
> chore: Update ocamlopt flags for dwarf & compact unwind

- src/binaryen_stubs_memory.js
- src/memory.ml
- src/memory.mli
- test/test.ml
As per request by @ospencer because `name` isn't really correct.
> feat!: Rename segment name to data

- README.md
- test/config/ocamlopt_flags.ml
Those flags completely break Mac M1, so we don't want to recommend them. People will just need to deal with the compact unwind warning on some system configurations 🤷
> chore: Remove flags that completely bork Mac M1

- src/binaryen_stubs_expressions.c
- src/binaryen_stubs_expressions.js
- src/expression.ml
- src/expression.mli
- test/test.ml
Tested this locally with Grain.
> fix!: Expression.Return.get_value can be null

- binaryen.opam
- esy.lock/index.json
- package.json
- src/binaryen_stubs_features.c
- src/binaryen_stubs_features.js
- src/binaryen_stubs_ops.c
- src/binaryen_stubs_ops.js
- src/module.ml
- src/module.mli
- test/test.ml
I believe this is everything we need for Binaryen version_107. There were some other changes related to SIMD but we don't support that yet.
@ospencer can you review https://github.com/WebAssembly/binaryen/compare/version_106...version_107 to make sure I got everything changed/new?
> feat!: Update libbinaryen to 107

- src/passes.ml
- src/passes.mli
This is only run during the default passes if the module has GC enabled, so not a big deal, but we should have it for completion.
> feat: Add signature_pruning pass

- src/binaryen_stubs_types.c
- src/binaryen_stubs_types.js
- src/type.ml
- src/type.mli
While digging into v108 of binaryen for the changes to externref (switched to anyref), I noticed that we didn't have these 3 reference types.
@ospencer what would it take to test these in our setup?
> feat: Add eqref, i31ref, and dataref types

- .github/workflows/release.yml
Closes #164
This upgrades release-please-action to utilize the fix in https://github.com/googleapis/release-please/releases/tag/v14.17.2 which solves the issue outlined in #164
> chore: Upgrade to release-please-action that fixes issue linking

- src/expression.ml
- src/expression.mli
While working on the v110 bindings, I noticed that this function didn't actually allow the correct number of arguments.
> fix!: Properly accept the size argument to Memory_init.make

- src/binaryen_stubs_expressions.js
- test/test.expected
- test/test.ml
This is super broken. Here are the fixes.
I blame @ospencer for having me change to a `switch` and blame myself for forgetting how `switch` works in JS.
> fix: Properly handle load & store instructions in JS

- src/passes.ml
- src/passes.mli
- test/test.ml
Closes #177 
I moved gsi to align with ordering in binaryen (so I can keep track easier).
> feat: Add gufa & gufa_optimizing passes

- .github/workflows/release.yml
We could bump to 0.21.0 but it feels better to become `0.20.1`. What do you think @ospencer?
> chore: Ensure non-breaking features are released as patch before 1.0

- .github/workflows/opam.yml
Same changes as https://github.com/grain-lang/libbinaryen/pull/77
> chore(ci): Cleanup hacks in opam CI & update matrix to 4.14.1

- .github/workflows/esy.yml
Our CI is failing on Windows because esy 0.7 fails to build our pretty old version of cmake. I have a new version in the works but that'll be included in libbinaryen 113 so I'm just restricting esy in our CI for this release.
> chore(ci): Restrict esy to 0.6 until our cmake supports 0.7

- binaryen.opam
- esy.lock/index.json
- esy.lock/opam/js_of_ocaml-compiler.6.0.1/opam
- package.json
- src/expression.js
- src/module.js
- test/dune
- test/test.ml
I'm not sure what to do with esy.lock changes
> chore!: Require jsoo >= 6.0
